import os, json, time, requests
from pathlib import Path

for file in ['.env','scripts/.secrets/notion.env']:
    p=Path(file)
    if p.exists():
        for line in p.read_text().splitlines():
            if '=' in line and not line.strip().startswith('#'):
                k,v=line.split('=',1); os.environ.setdefault(k.strip(),v.strip().strip('"'))

H={'Authorization':'Bearer '+os.environ['NOTION_TOKEN'],'Notion-Version':'2022-06-28','Content-Type':'application/json'}
PROD_DB='375207e6-f145-8111-bba0-e132fd820542'
OUT=Path('[F2] memory/outputs/saude-sao-sebastiao/notion'); OUT.mkdir(parents=True, exist_ok=True)

# Versão limpa: cada dia tem 1 protagonista de feed + 5 stories alternados dentro do pilar + cronogramas de captação.
items=[
{'date':'2026-07-17','date_br':'17/07/2026','weekday':'Sexta','pilar':'Flexível / Bastidores / Prestação','feed':'Unidade Mista + SAMU + Referências Regionais','formato':'Feed de fotos ou reels curto','headline':'Quando a situação aperta, a rede precisa estar pronta para orientar o caminho certo.','legenda':'Na urgência, cada minuto importa — e entender o fluxo também faz parte do cuidado. A Unidade Mista acolhe, avalia e classifica o risco; o SAMU atua nas situações de emergência; e, quando o caso precisa ir além do município, a rede organiza o encaminhamento com responsabilidade. Procure sua unidade de referência para orientações de rotina e acione o 192 em situações de urgência real.','roteiro':['Abrir com fachada/entrada da Unidade Mista ou equipe em prontidão, sem pacientes identificáveis.','Mostrar detalhe de classificação de risco, sala de observação ou material de trabalho sem dados sensíveis.','Inserir SAMU/192 como parte do fluxo de urgência real, não como chamada genérica.','Explicar referência regional de forma simples: quando o município organiza o caminho para outro serviço.','Fechar com orientação prática: unidade de referência para rotina; 192 para urgência real.'],'stories':[('Unidade Mista','Entrada, recepção ou ambiente preparado. Texto: “Quando a situação aperta, a Unidade Mista acolhe e classifica o risco.”'),('SAMU / 192','Ambulância, mochila ou equipe checando equipamento. Texto: “Na urgência de verdade, o 192 orienta e chega para salvar tempo.”'),('Referências Regionais','Mapa simples ou veículo/equipe sem placa. Texto: “Quando precisa ir além do município, a rede organiza o caminho com responsabilidade.”'),('Julho Amarelo no fluxo','Card/laço, caderneta ou material educativo. Texto: “Hepatite pode ser silenciosa; informação, vacina e teste ajudam na prevenção.”'),('Fechamento de serviço','Equipe/ambiente da rede. Texto: “Serviço certo, no momento certo, ajuda o cuidado a chegar melhor.”')], 'captar_extra':'Sexta também tem Psiquiatria/Psicologia no Espaço Cuidar e EMULTI nas academias/visitas. Captar se houver imagem segura; publicar hoje só se couber como humanização, fluxo ou oportunidade forte.'},
{'date':'2026-07-20','date_br':'20/07/2026','weekday':'Segunda','pilar':'Atenção Básica / Território','feed':'PNI / sala de vacina — Hepatite B','formato':'Reels serviço','headline':'A proteção contra a hepatite B começa perto de casa, na unidade de referência.','legenda':'A vacina contra a hepatite B é uma das formas mais importantes de prevenção — e a orientação começa na Atenção Básica. Nas unidades, as equipes acompanham a caderneta, orientam famílias e ajudam cada pessoa a entender quais cuidados precisa manter em dia. Procure sua UBS/PSF para verificar sua situação vacinal e tirar dúvidas com a equipe.','roteiro':['Abrir com sala de vacina, caderneta ou profissional preparando orientação.','Mostrar PNI como rotina de cuidado da Atenção Básica, sem dados de lote ou usuário.','Trazer benefício claro: vacina como prevenção contra hepatite B.','Conectar com território: PSF/UBS como primeiro lugar para perguntar.','Fechar com CTA para conferir caderneta na unidade.'],'stories':[('Sala de vacina / PNI','Imagem de caderneta sem dados ou equipe orientando. Texto: “Vacina em dia é proteção que começa na unidade.”'),('ACS / busca ativa','ACS em rota ou orientação sem dados. Texto: “No território, a equipe ajuda a lembrar quem precisa atualizar o cuidado.”'),('UBS/PSF de referência','Fachada/recepção segura. Texto: “Sua unidade é o primeiro lugar para tirar dúvidas sobre vacina e prevenção.”'),('Grupos prioritários','Material educativo sobre criança, adulto, idoso ou gestante. Texto: “A proteção vale para todas as fases da vida.”'),('Farmácia/continuidade','Prateleira/organização sem usuário. Texto: “Prevenção e acompanhamento caminham juntos na rede.”')], 'captar_extra':'Segunda tem Pediatria/Cardiologia no Espaço Cuidar e EMULTI nas academias/território. Se não reforçar Atenção Básica/continuidade, guardar para terça.'},
{'date':'2026-07-21','date_br':'21/07/2026','weekday':'Terça','pilar':'Serviços Especializados','feed':'Oftalmologia','formato':'Carrossel ou reels se houver imagem forte','headline':'Cuidar da visão também é prevenir complicações que podem mudar a rotina de uma família.','legenda':'A oftalmologia fortalece o cuidado especializado na rede municipal, especialmente para pessoas que precisam acompanhar visão, diabetes, glaucoma, catarata ou dificuldades visuais na escola. O acesso acontece a partir da orientação da UBS/PSF e da regulação municipal, mantendo o cuidado organizado entre a unidade de origem e o serviço especializado.','roteiro':['Abrir com consultório/equipamento/material visual, sem paciente exposto.','Mostrar a visão como cuidado especializado que impacta rotina, estudo e autonomia.','Citar grupos prioritários de forma educativa: idosos, diabéticos, crianças e hipertensos.','Explicar fluxo: UBS/PSF orienta, encaminha e a regulação organiza.','Fechar reforçando procurar a unidade de referência.'],'stories':[('Oftalmologia','Consultório/equipamento. Texto: “Visão também precisa de acompanhamento no tempo certo.”'),('Espaço Cuidar / Pneumologia','Ambiente/fluxo do dia, se houver. Texto: “Na terça, o especializado ajuda a rede a seguir o cuidado.”'),('CEO / Saúde Bucal','Consultório odontológico sem paciente. Texto: “Quando o caso precisa de continuidade, o encaminhamento organiza o cuidado.”'),('EMULTI / Fisioterapia','Exercício orientado sem exposição. Texto: “Reabilitação também é cuidado especializado feito em etapas.”'),('Fluxo de acesso','Guia coberta/recepção. Texto: “A UBS orienta, encaminha e acompanha o retorno do usuário.”')], 'captar_extra':'Terça é dia natural de usar materiais especializados guardados, desde que estejam dentro do tema e com autorização de imagem.'},
{'date':'2026-07-22','date_br':'22/07/2026','weekday':'Quarta','pilar':'Vigilância / Prevenção','feed':'Vigilância Sanitária','formato':'Reels educativo','headline':'Tem proteção que quase ninguém vê, mas ajuda a cidade inteira a adoecer menos.','legenda':'A Vigilância Sanitária atua nos bastidores da prevenção, orientando serviços, acompanhando ambientes e reduzindo riscos no que a população consome e utiliza. É um trabalho de cuidado coletivo: quando a equipe orienta, fiscaliza e corrige riscos, a saúde de todos fica mais protegida.','roteiro':['Abrir com equipe, checklist ou ambiente fiscalizado sem identificação.','Mostrar VISA como prevenção coletiva, não apenas fiscalização.','Explicar exemplos sem expor estabelecimentos: alimentos, serviços, salões, medicamentos/cosméticos.','Conectar com atitude prática da população: observar, cuidar e denunciar quando necessário.','Fechar com “prevenção também acontece antes do problema aparecer”.'],'stories':[('Vigilância Sanitária','Checklist/prancheta sem identificar local. Texto: “Prevenção também é orientar antes do problema acontecer.”'),('Endemias','Agente em campo ou material dengue. Texto: “Dentro de casa, pequenos cuidados evitam grandes riscos.”'),('PNI / prevenção','Caderneta ou sala de vacina. Texto: “Vacina em dia também faz parte da vigilância da saúde.”'),('Ginecologia como prevenção','Se houver captação no Espaço Cuidar: material educativo/ambiente. Texto: “Especialidade só entra aqui quando vira orientação e prevenção.”'),('Fechamento','Equipe/ambiente. Texto: “Equipe e população prevenindo juntas protegem mais.”')], 'captar_extra':'Quarta tem Ginecologia no Espaço Cuidar, EMULTI em Flexeiras/Lagoa Seca/Gongo/Maracujá e educação física. Publicar especializado só se virar prevenção/orientação.'},
{'date':'2026-07-23','date_br':'23/07/2026','weekday':'Quinta','pilar':'Rede de Apoio / Humanização','feed':'Maternidade e puerpério','formato':'Reels humanizado','headline':'Depois do nascimento, o cuidado continua — com orientação, acolhimento e rede por perto.','legenda':'O cuidado com a gestante, a puérpera e o recém-nascido não termina no parto. Ele segue na orientação, no acompanhamento, nos testes, na vacinação e no apoio que a rede oferece para que mãe e bebê atravessem esse momento com mais segurança. Humanizar é estar presente também depois que a família volta para casa.','roteiro':['Abrir com ambiente materno-infantil preparado, sem exposição de mãe/bebê sem autorização.','Mostrar orientação profissional, material de aleitamento, teste ou vacina RN de forma segura.','Explicar que puerpério precisa de acompanhamento e escuta.','Conectar UBS, maternidade, Melhor em Casa/EMULTI quando houver continuidade.','Fechar chamando para orientação na unidade de referência.'],'stories':[('Maternidade','Leito/ambiente/material preparado sem expor bebê. Texto: “O cuidado continua depois do nascimento.”'),('Aleitamento / puerpério','Material educativo ou profissional orientando. Texto: “Orientação no puerpério dá mais segurança para mãe e bebê.”'),('UBS como continuidade','Caderneta/recepção segura. Texto: “A unidade acompanha a família no retorno para casa.”'),('EMULTI / visita domiciliar','Equipe se preparando ou recurso de cuidado. Texto: “Quando precisa, a rede também chega mais perto da família.”'),('Fechamento humano','Mãos/equipe/ambiente. Texto: “Acolher também é cuidar no tempo de cada família.”')], 'captar_extra':'Quinta tem Cirurgia Geral no Espaço Cuidar, EMULTI em Flexeiras e Janaina à tarde. Especializado só publica se reforçar acolhimento/continuidade; senão guardar.'},
{'date':'2026-07-24','date_br':'24/07/2026','weekday':'Sexta','pilar':'Flexível / Bastidores / Prestação','feed':'Farmácia Municipal / continuidade do tratamento','formato':'Feed de fotos de bastidores','headline':'Por trás de cada tratamento em dia, existe uma rotina de organização que não pode falhar.','legenda':'A Farmácia Municipal também faz parte da continuidade do cuidado. Conferência, organização e orientação ajudam o medicamento a chegar com mais segurança a quem depende do tratamento. Nos bastidores, esse trabalho sustenta o acompanhamento feito pelas unidades e fortalece o funcionamento da rede.','roteiro':['Abrir com prateleiras/organização/conferência sem dados de usuários.','Mostrar a farmácia como bastidor essencial, não só entrega de medicamento.','Conectar com UBS/PSF: tratamento precisa de acompanhamento.','Inserir prestação qualitativa da semana com serviços de apoio nos stories.','Fechar com orientação responsável: procure a unidade para informações sobre seu tratamento.'],'stories':[('Farmácia Municipal','Prateleira/conferência. Texto: “Medicamento organizado é mais segurança para quem segue tratamento.”'),('Almoxarifado / insumos','Caixas/controle sem marca sensível. Texto: “Bastidor organizado ajuda a rede a funcionar.”'),('Espaço Cuidar','Ambiente/fluxo se houver. Texto: “Especializado entra hoje só quando reforça continuidade do cuidado.”'),('Academia da Saúde','Grupo/atividade. Texto: “Prevenção também sustenta tratamento e qualidade de vida.”'),('Fechamento da semana','Equipe/ambiente. Texto: “Cuidar também é manter o fluxo funcionando.”')], 'captar_extra':'Sexta tem Psiquiatria/Psicologia, fisioterapia e educação física. Captar para banco; publicar somente se couber como prestação, bastidor ou humanização forte.'},
{'date':'2026-07-27','date_br':'27/07/2026','weekday':'Segunda','pilar':'Atenção Básica / Território','feed':'UBS/PSF — orientação sobre hepatites','formato':'Reels chamada','headline':'Antes da dúvida virar preocupação, a orientação começa na sua unidade de referência.','legenda':'Na véspera do Dia Mundial das Hepatites Virais, a Atenção Básica tem um papel essencial: orientar, identificar dúvidas, organizar o caminho para vacina, testes e acompanhamento. A UBS/PSF é a porta de entrada para quem precisa entender como se prevenir e onde buscar cuidado com segurança.','roteiro':['Abrir com UBS/PSF, recepção ou equipe orientando.','Mostrar território: unidade como primeiro ponto de orientação.','Conectar hepatites com vacina, testes e acompanhamento, sem prometer ação não confirmada.','Alternar nos stories laboratório, PNI, ACS e PSFs rurais.','Fechar com CTA para procurar unidade de referência.'],'stories':[('UBS/PSF','Fachada/recepção. Texto: “Na dúvida, comece pela sua unidade de referência.”'),('ACS / território','Agente em rota. Texto: “No território, a equipe ajuda a informação chegar mais longe.”'),('PNI','Caderneta/sala de vacina. Texto: “Hepatite B tem prevenção com vacina.”'),('Laboratório / testagem','Material de coleta sem dados. Texto: “Quando indicado, o exame ajuda a organizar o cuidado.”'),('PSFs rurais','Imagem segura de rota/unidade. Texto: “A orientação precisa chegar também nas comunidades.”')], 'captar_extra':'Segunda tem Pediatria/Cardiologia e EMULTI. Usar especializado só como continuidade da Atenção Básica; se não, guardar para terça.'},
{'date':'2026-07-28','date_br':'28/07/2026','weekday':'Terça','pilar':'Serviços Especializados / Julho Amarelo','feed':'Dia Mundial das Hepatites Virais — vacina, teste e tratamento','formato':'Reels principal do mês','headline':'Hepatite pode ser silenciosa; informação, vacina e teste ajudam o cuidado chegar a tempo.','legenda':'Neste Dia Mundial das Hepatites Virais, o alerta é simples e importante: prevenir, testar e tratar salva vidas. A rede municipal orienta a população pela Atenção Básica, organiza vacinação, encaminha exames quando indicado e acompanha o cuidado de forma responsável. Procure sua unidade de referência e tire suas dúvidas com a equipe de saúde.','roteiro':['Abrir com laço/card Julho Amarelo ou equipe em orientação.','Mostrar vacina/caderneta e material educativo.','Inserir laboratório/testagem sem resultados ou dados.','Mostrar farmácia/acompanhamento como continuidade quando houver indicação.','Fechar com UBS como caminho para orientação.'],'stories':[('Julho Amarelo','Card/laço/equipe. Texto: “Hepatite pode ser silenciosa. Informação salva tempo no cuidado.”'),('PNI / vacina','Caderneta sem dados. Texto: “Vacina é uma das formas de prevenção contra hepatite B.”'),('Laboratório / testes','Material de coleta sem identificação. Texto: “Quando indicado, testar ajuda a cuidar mais cedo.”'),('Farmácia / tratamento','Organização de medicamento sem usuário. Texto: “Tratamento precisa de acompanhamento e orientação.”'),('UBS / fluxo','Recepção/equipe. Texto: “Procure sua unidade de referência e tire suas dúvidas.”')], 'captar_extra':'Por ser terça, incorporar materiais especializados guardados apenas se reforçarem hepatites, prevenção, testagem, tratamento ou fluxo de cuidado.'},
{'date':'2026-07-29','date_br':'29/07/2026','weekday':'Quarta','pilar':'Vigilância / Prevenção','feed':'Endemias + prevenção integrada','formato':'Carrossel ou reels de campo','headline':'Prevenção não acontece em um só lugar: ela começa em casa, passa pela rua e chega aos serviços.','legenda':'Depois do alerta do Julho Amarelo, a prevenção continua na rotina da cidade. Endemias, Vigilância Sanitária, vacinação e orientação nas unidades fazem parte de uma mesma rede de cuidado: reduzir riscos antes que eles virem problema. Quando equipe e população fazem sua parte, a proteção chega mais longe.','roteiro':['Abrir com ACE/endemias em campo ou checklist visual.','Mostrar ação concreta: água parada, orientação domiciliar ou material educativo.','Alternar VISA e PNI nos stories como prevenção integrada.','Trazer hepatites como continuidade da campanha, sem repetir peça principal.','Fechar com responsabilidade compartilhada.'],'stories':[('Endemias','ACE em campo/quintal. Texto: “Eliminar criadouros ainda é cuidado de todos os dias.”'),('VISA','Checklist/ambiente sem identificação. Texto: “Segurança sanitária também protege a população.”'),('PNI','Caderneta/sala de vacina. Texto: “Vacina em dia é prevenção que continua.”'),('Hepatites / orientação','Material educativo. Texto: “Depois da campanha, a orientação segue na rotina da unidade.”'),('Fechamento integrado','Equipe/território. Texto: “Prevenção funciona melhor quando a cidade participa.”')], 'captar_extra':'Quarta tem Ginecologia, EMULTI e educação física. Especializado só entra se virar prevenção/orientação; caso contrário, banco para terça.'},
{'date':'2026-07-30','date_br':'30/07/2026','weekday':'Quinta','pilar':'Rede de Apoio / Humanização','feed':'CAPS / rede de apoio sem preconceito','formato':'Reels humanizado','headline':'Cuidar da saúde mental é construir rotina, vínculo e respeito — sem julgamento.','legenda':'No cuidado em saúde mental, acolhimento e continuidade fazem diferença. O CAPS, a Atenção Básica, o Melhor em Casa, a EMULTI e a rede de apoio ajudam a acompanhar pessoas e famílias com mais escuta, orientação e respeito. Humanizar é entender que cada história precisa de cuidado sem preconceito.','roteiro':['Abrir com ambiente do CAPS/oficina/equipe, sem identificar usuários.','Mostrar cuidado como rotina: escuta, grupo, oficina, acolhimento.','Alternar rede de apoio nos stories: assistência, família, domicílio, EMULTI.','Evitar exposição sensível; usar planos de ambiente, mãos e materiais.','Fechar com orientação para buscar apoio na rede.'],'stories':[('CAPS','Sala/oficina/material. Texto: “Saúde mental precisa de rotina, vínculo e respeito.”'),('Assistência Social','Atendimento/ambiente sem exposição. Texto: “Rede de apoio também é orientar a família no caminho certo.”'),('Melhor em Casa','Equipe/material domiciliar. Texto: “Quando o cuidado precisa chegar mais perto, a rede se organiza.”'),('EMULTI','Profissional orientando/exercício. Texto: “Cuidado multiprofissional ajuda a sustentar a continuidade.”'),('Fechamento sem preconceito','Ambiente/equipe. Texto: “Pedir ajuda é parte do cuidado.”')], 'captar_extra':'Quinta tem Cirurgia Geral e EMULTI. Publicar especializado só se reforçar acolhimento/continuidade; senão guardar.'},
{'date':'2026-07-31','date_br':'31/07/2026','weekday':'Sexta','pilar':'Flexível / Bastidores / Prestação','feed':'Fechamento do Julho Amarelo — rede em continuidade','formato':'Reels balanço','headline':'O Julho Amarelo termina, mas a prevenção precisa continuar na rotina da rede.','legenda':'O mês de conscientização reforçou uma mensagem que segue valendo todos os dias: informação, vacina, testagem quando indicada e acompanhamento ajudam a proteger vidas. O trabalho continua nas unidades, no território, no laboratório, na farmácia e nas equipes que orientam a população com responsabilidade. Prevenção não acaba com a campanha — ela segue no cuidado diário.','roteiro':['Abrir com montagem de imagens seguras do mês/equipes.','Mostrar PNI, laboratório, UBS e farmácia como continuidade do cuidado.','Reconhecer equipes sem usar números não confirmados.','Evitar balanço genérico: falar da continuidade pós-campanha.','Fechar com CTA para procurar unidade e manter prevenção em dia.'],'stories':[('Julho Amarelo','Laço/card/equipe. Texto: “A campanha termina, mas a prevenção continua.”'),('UBS/PSF','Unidade/equipe. Texto: “A orientação segue perto da população.”'),('PNI + Laboratório','Caderneta/coleta sem dados. Texto: “Vacina e teste, quando indicados, ajudam a cuidar mais cedo.”'),('Farmácia / acompanhamento','Organização segura. Texto: “Tratamento e acompanhamento precisam de continuidade.”'),('Fechamento da rede','Equipe/território. Texto: “Cuidar é manter a rede em movimento todos os dias.”')], 'captar_extra':'Sexta tem Psiquiatria/Psicologia, fisioterapia e educação física. Só usar se entrar como balanço, humanização ou oportunidade forte; senão, banco.'}
]

cron={
'Segunda':['Espaço Cuidar: Pediatria + Cardiologia — captar como continuidade da Atenção Básica; se não reforçar, guardar para terça.','EMULTI/Fisioterapia: Academia Polo manhã/tarde; Academia Rancho manhã/tarde; Academia Cana Brava manhã/tarde; Lagoa Seca/Gongo/Maracujá; Ranielle visita domiciliar pela manhã.','Psicologia: Gabriel em Peroba; Naely, Rayane e Thalita no Espaço Cuidar.','Nutrição ativa nas unidades; Emanoela com grupo no Rancho quando confirmado.'],
'Terça':['Espaço Cuidar: Pneumologia — pilar natural de Serviços Especializados.','EMULTI/Fisioterapia: Academia Polo tarde; Academia Rancho tarde; Academia Cana Brava manhã/tarde; Lagoa Seca/Gongo/Maracujá; Ranielle visita domiciliar.','Psicologia: Gabriel em São José/Peroba; Naely e Luciana no Espaço Cuidar; Thalita no Espaço Cuidar.','Educação Física: Larisse na Academia Cana Brava.'],
'Quarta':['Espaço Cuidar: Ginecologia — publicar só se reforçar prevenção/orientação.','Oftalmologia: primeira quarta do mês quando houver agenda confirmada.','EMULTI/Fisioterapia: UBS Flexeiras; Lagoa Seca/Gongo/Maracujá; Lyvia em Mata/Cana Brava; Ranielle visita domiciliar.','Educação Física: Anny em Flexeiras; Larisse na Academia Polo.'],
'Quinta':['Espaço Cuidar: Cirurgia Geral — publicar só se reforçar acolhimento/continuidade.','EMULTI/Fisioterapia: UBS Flexeiras; Academia Polo/Rancho/Cana Brava; Janaina em Pedra Preta/Capim Branco; Ranielle visita.','Psicologia: Rayane e Thalita no Espaço Cuidar.','Educação Física: Anny PV Mata; Larisse no Posto São José.'],
'Sexta':['Espaço Cuidar: Psiquiatria — publicar só se couber como humanização/rede/oportunidade forte.','Psicologia: palestras/visitas e Rayane/Thalita no Espaço Cuidar; cuidado extremo com privacidade.','EMULTI/Fisioterapia: Academia Polo manhã/tarde; Academia Rancho manhã; Academia Cana Brava manhã/tarde; UBS Flexeiras; Ranielle visita; Janaina Curralinho/Terra Nova.','Educação Física: Anny Flexeiras/Polo; Larisse Academia Cana Brava.','Nutrição ativa nas unidades: captar se houver atendimento/grupo em rota.']
}

def rt(text): return [{'type':'text','text':{'content':str(text)[:2000]}}]
def block(t,text='',**extra):
    if t=='divider': return {'object':'block','type':'divider','divider':{}}
    obj={'rich_text':rt(text)}; obj.update(extra); return {'object':'block','type':t,t:obj}

def list_children(block_id):
    out=[]; cursor=None
    while True:
        params={'page_size':100}
        if cursor: params['start_cursor']=cursor
        r=requests.get(f'https://api.notion.com/v1/blocks/{block_id}/children',headers=H,params=params,timeout=30); r.raise_for_status()
        data=r.json(); out += data.get('results',[])
        if not data.get('has_more'): break
        cursor=data.get('next_cursor')
    return out

def archive_children(page_id):
    children=list_children(page_id)
    for b in children:
        rr=requests.patch(f'https://api.notion.com/v1/blocks/{b["id"]}',headers=H,json={'archived':True},timeout=30)
        if rr.status_code>=300: print('WARN archive', b['id'], rr.status_code, rr.text[:200])
        time.sleep(0.03)
    return len(children)

def find_by_title(title):
    cursor=None
    while True:
        payload={'page_size':100}
        if cursor: payload['start_cursor']=cursor
        r=requests.post(f'https://api.notion.com/v1/databases/{PROD_DB}/query',headers=H,json=payload,timeout=30); r.raise_for_status(); data=r.json()
        for p in data.get('results',[]):
            t=''.join(x.get('plain_text','') for x in p.get('properties',{}).get('Nome',{}).get('title',[]))
            if t==title: return p
        if not data.get('has_more'): return None
        cursor=data.get('next_cursor')

def blocks(it):
    out=[block('heading_1',f"{it['date_br']} — {it['weekday']} — VERSÃO LIMPA"),
         block('callout','Página limpa em 17/07: programação antiga arquivada para não confundir. Esta versão aplica rotação por pilar, 1 protagonista no feed, 5 stories alternados e cronogramas de captação separados da publicação.',icon={'type':'emoji','emoji':'🧭'}),
         block('heading_2','1. Pilar do dia'), block('paragraph',it['pilar']),
         block('heading_2','2. Protagonista do feed'), block('bulleted_list_item',f"Serviço/setor que ganha força: {it['feed']}"), block('bulleted_list_item',f"Formato: {it['formato']}"),
         block('heading_2','3. Headline do feed'), block('paragraph',it['headline']),
         block('heading_2','4. Legenda sugerida do feed'), block('paragraph',it['legenda']),
         block('heading_2','5. Roteiro do feed')]
    for x in it['roteiro']: out.append(block('numbered_list_item',x))
    out += [block('heading_2','6. Stories — rotação dentro do pilar')]
    for i,(name,desc) in enumerate(it['stories'],1):
        out += [block('heading_3',f'Story {i} — {name}'), block('paragraph',desc)]
    out += [block('heading_2','7. Cronogramas do dia para lembrar captação')]
    for x in cron[it['weekday']]: out.append(block('bulleted_list_item',x))
    out += [block('paragraph',it['captar_extra']),
            block('heading_2','8. Regra de decisão'),
            block('bulleted_list_item','Publicar hoje: apenas o que reforça o pilar e o protagonista definido para o feed.'),
            block('bulleted_list_item','Captar e guardar: materiais bons de setores que estão acontecendo, mas que não reforçam o pilar do dia.'),
            block('bulleted_list_item','Especializados fora da terça: só entram se forem continuidade, prevenção, humanização ou oportunidade forte dentro do pilar.'),
            block('heading_2','9. Cuidados fixos'),
            block('bulleted_list_item','Não expor pacientes, documentos, prontuários, resultados, CNS, placas ou telas de sistemas.'),
            block('bulleted_list_item','Confirmar agenda, números, horários e disponibilidade antes de publicar.'),
            block('bulleted_list_item','Preferir serviço real acontecendo, linguagem acessível, tom humano e utilidade pública.')]
    return out

updated=[]
START_DATE=os.environ.get('START_DATE')
for it in items:
    if START_DATE and it['date'] < START_DATE:
        continue
    title=f"SMS São Sebastião — {it['date_br']} — {it['weekday']}"
    page=find_by_title(title)
    if not page: raise RuntimeError('Não encontrada: '+title)
    pid=page['id']
    archived=archive_children(pid)
    props={'Status':{'select':{'name':'Aguardando aprovação'}},
           'Briefing/Roteiro':{'rich_text':rt(f"VERSÃO LIMPA 17/07 | {it['pilar']} | Feed: {it['feed']} | Headline: {it['headline']} | 5 stories alternados dentro do pilar + cronogramas de captação separados.")},
           'Observações':{'rich_text':rt('Conteúdo antigo da página arquivado/limpo em 17/07 para evitar confusão. Aplicadas regras: rotação de setores dentro do pilar, um protagonista no feed, legendas/headlines específicas baseadas no Cofre e cronogramas de captação separados da publicação.')}}
    rr=requests.patch(f'https://api.notion.com/v1/pages/{pid}',headers=H,json={'properties':props},timeout=30)
    if rr.status_code>=300: raise RuntimeError(rr.text)
    ch=blocks(it)
    for i in range(0,len(ch),90):
        r=requests.patch(f'https://api.notion.com/v1/blocks/{pid}/children',headers=H,json={'children':ch[i:i+90]},timeout=30)
        if r.status_code>=300: raise RuntimeError(f'{title} {r.status_code}: {r.text}')
        time.sleep(0.05)
    updated.append({'date':it['date_br'],'title':title,'page_id':pid,'archived_old_blocks':archived,'url':page.get('url')})
    time.sleep(0.1)

res={'ok':True,'updated_count':len(updated),'updated':updated,'note':'Páginas 17/07 a 31/07 limpas e reescritas.'}
(OUT/'2026-07-17-notion-calendario-limpo-rotacao-pilares-result.json').write_text(json.dumps(res,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps(res,ensure_ascii=False,indent=2))
